name: Deploy to GitHub Pages

permissions:
  contents: write    # allow pushing commits
  pages: write       # allow Pages deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Uncomment if you need to rebuild:
      # - name: Build web-mobile
      #   run: |
      #     cocos-creator-cli --path . --build \
      #       "platform=web-mobile;debug=false"

      - name: Deploy to gh-page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-page
          publish_dir: build/web-mobile
